services:
  gradio:
    container_name: invsr-gradio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7860:7860 # PORT by default is 7860
    volumes:
      - invsr_weights:/invsr/weights/

volumes:
  invsr_weights:
    name: invsr_weights
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./weights

networks:
  default:
    name: invsr_net